all: Surv_SpaceAgeTime_ByType_withUnknownType_Const_Paed_MMC.dll Surv_SpaceAgeTime_ByType_withUnknownType_Const_Paed_MMC_RW.dll Surv_SpaceAgeTime_ByType_withUnknownType.dll Surv_SpaceAgeTime_ByType_withUnknownType_RW.dll Surv_SpaceAgeTime.dll Surv_SpaceAgeTime_RW.dll  
	# Comment here preserves the prior tab
Surv_SpaceAgeTime_ByType_withUnknownType_Const_Paed_MMC.dll: Surv_SpaceAgeTime_ByType_withUnknownType_Const_Paed_MMC.cpp
	Rscript --vanilla -e "TMB::compile('Surv_SpaceAgeTime_ByType_withUnknownType_Const_Paed_MMC.cpp', '-O1 -g',DLLFLAGS='')"
Surv_SpaceAgeTime_ByType_withUnknownType_Const_Paed_MMC_RW.dll: Surv_SpaceAgeTime_ByType_withUnknownType_Const_Paed_MMC_RW.cpp
	Rscript --vanilla -e "TMB::compile('Surv_SpaceAgeTime_ByType_withUnknownType_Const_Paed_MMC_RW.cpp', '-O1 -g',DLLFLAGS='')"
Surv_SpaceAgeTime_ByType_withUnknownType.dll: Surv_SpaceAgeTime_ByType_withUnknownType.cpp
	Rscript --vanilla -e "TMB::compile('Surv_SpaceAgeTime_ByType_withUnknownType.cpp', '-O1 -g',DLLFLAGS='')"
Surv_SpaceAgeTime_ByType_withUnknownType_RW.dll: Surv_SpaceAgeTime_ByType_withUnknownType_RW.cpp
	Rscript --vanilla -e "TMB::compile('Surv_SpaceAgeTime_ByType_withUnknownType_RW.cpp', '-O1 -g',DLLFLAGS='')"
Surv_SpaceAgeTime.dll: Surv_SpaceAgeTime.cpp
	Rscript --vanilla -e "TMB::compile('Surv_SpaceAgeTime.cpp', '-O1 -g',DLLFLAGS='')"
Surv_SpaceAgeTime_RW.dll: Surv_SpaceAgeTime_RW.cpp
	Rscript --vanilla -e "TMB::compile('Surv_SpaceAgeTime_RW.cpp', '-O1 -g',DLLFLAGS='')"

clean:
	rm -rf *.dll
