all: threemc.dll
	# Comment here preserves the prior tab
threemc.dll: threemc.cpp
	Rscript --vanilla -e "TMB::compile('threemc.cpp', framework = 'TMBad', '-I"/src" -O1 -g', DLLFLAGS='')"

clean:
	rm -rf *.dll
