all: Surv_SpaceAgeTime_ByType_withUnknownType.dll Surv_SpaceAgeTime.dll
	# Comment here preserves the prior tab
Surv_SpaceAgeTime_ByType_withUnknownType.dll: Surv_SpaceAgeTime_ByType_withUnknownType.cpp
	Rscript --vanilla -e "TMB::compile('Surv_SpaceAgeTime_ByType_withUnknownType.cpp', '-O1 -g',DLLFLAGS='')"
Surv_SpaceAgeTime.dll: Surv_SpaceAgeTime.cpp
	Rscript --vanilla -e "TMB::compile('Surv_SpaceAgeTime.cpp', '-O1 -g',DLLFLAGS='')"

clean:
	rm -rf *.dll
